# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/work/fpga_vcu1525/fpga_pcie/xdma_0_ex/xdma_0_ex.srcs/sources_1/ip/blk_mem_1024D32W/blk_mem_1024D32W.xci
# IP: The module: 'blk_mem_1024D32W' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/fpga_vcu1525/fpga_pcie/xdma_0_ex/xdma_0_ex.srcs/sources_1/ip/blk_mem_1024D32W/blk_mem_1024D32W_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_1024D32W'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/work/fpga_vcu1525/fpga_pcie/xdma_0_ex/xdma_0_ex.srcs/sources_1/ip/blk_mem_1024D32W/blk_mem_1024D32W.xci
# IP: The module: 'blk_mem_1024D32W' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/fpga_vcu1525/fpga_pcie/xdma_0_ex/xdma_0_ex.srcs/sources_1/ip/blk_mem_1024D32W/blk_mem_1024D32W_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_1024D32W'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
