# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/work/fpga_vcu1525/fpga_pcie/cryptonight_pcie_top/xdma_0_ex.srcs/sources_1/ip/axi4_lite_amm_bridge/axi4_lite_amm_bridge.xci
# IP: The module: 'axi4_lite_amm_bridge' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/fpga_vcu1525/fpga_pcie/cryptonight_pcie_top/xdma_0_ex.srcs/sources_1/ip/axi4_lite_amm_bridge/axi4_lite_amm_bridge.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_lite_amm_bridge'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/work/fpga_vcu1525/fpga_pcie/cryptonight_pcie_top/xdma_0_ex.srcs/sources_1/ip/axi4_lite_amm_bridge/axi4_lite_amm_bridge_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_lite_amm_bridge'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/work/fpga_vcu1525/fpga_pcie/cryptonight_pcie_top/xdma_0_ex.srcs/sources_1/ip/axi4_lite_amm_bridge/axi4_lite_amm_bridge.xci
# IP: The module: 'axi4_lite_amm_bridge' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/fpga_vcu1525/fpga_pcie/cryptonight_pcie_top/xdma_0_ex.srcs/sources_1/ip/axi4_lite_amm_bridge/axi4_lite_amm_bridge.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_lite_amm_bridge'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/work/fpga_vcu1525/fpga_pcie/cryptonight_pcie_top/xdma_0_ex.srcs/sources_1/ip/axi4_lite_amm_bridge/axi4_lite_amm_bridge_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_lite_amm_bridge'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
