# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/work/fpga_vcu1525/fpga_pcie/cryptonight_pcie_top/imports/xilinx_pcie_xdma_ref_board.xdc

# IP: ip/xdma_0/xdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_0 || ORIG_REF_NAME==xdma_0} -quiet] -quiet
